// sample applications/countries-angular/src/app/app.component.ts
import {Component} from '@angular/core';
import {HttpClient} from '@angular/common/http';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  // Data/state for this component. In bigger applications this will live in a service or
  // state management solution (ngrx, akita), but for now we hold it inside this component.
  countries: Array<any> = [];
  countryName = '';
  currentCountry: any = null;

  // Url of external API to talk to (should be in
  // an environment variable or the like, in real life applications)
  url = 'https://restcountries.eu/rest/v2/name/';

  // constructor, DI of http client. IRL applications this should be in a Service.
  constructor(private http: HttpClient) {

  }

  // methods
  searchCountry(): void {
    if (this.countryName.length < 2) {
      return;
    }
    console.log(this.countryName); // demo

    // call external API endpoint
    this.http.get(this.url + this.countryName)
      .subscribe((response: any[]) => {
        console.log(response);  // demo
        this.countries = response;
      });
  }

  // Capture event and set the current country, which is then passed on to
  // the detail component
  onCurrentCountry(country: any) {
    this.currentCountry = country;
  }

  // Clear all variables;
  clear(){
    this.currentCountry = null;
    this.countries = [];
    this.countryName = ''
  }
}

<div class="container">
  <h1><img src="../assets/img/angular-logo.png" width="80"/> Angular Vacation Picker</h1>
  <p>I want to visit:</p>
  <input type="text"
         (keyup.enter)="searchCountry()"
         [(ngModel)]="countryName"
         class="form-control-lg"
         placeholder="country name...">
  <button class="btn btn-primary" (click)="searchCountry()">Search</button>
  <button class="btn btn-warning" (click)="clear()">Clear</button>
  <hr>
  <div class="row">
    <div class="col-6">
      <app-country-list
        [countries]="countries"
        (currentCountry)="onCurrentCountry($event)">
      </app-country-list>
    </div>
    <div class="col-6">
      <app-country-detail
        *ngIf="currentCountry"
        [country]="currentCountry">
      </app-country-detail>
    </div>
  </div>

</div>

// sample applications/countries-vue/src/App.vue
<template>
    <div class="container">
        <h1><img src="./assets/logo.png" height="100"/>Vue Vacation Picker</h1>
        <p>I want to visit:</p>
        <input class="form-control-lg"
               v-model="countryName"
               type="text"
               @keyup.enter="searchCountry"
               placeholder="country name...">
        <button @click="searchCountry"
                class="btn btn-primary">Search
        </button>
        <button class="btn btn-warning" @click="clear()">Clear</button>
        <hr>
        <div class="row">
            <div class="col-6">
                <!-- 1. Pass in the list of countries as a prop. Capture the setCountry event and fire local event handler -->
                <CountryList :countries="countries" @setCountry="setCountry($event)"/>
            </div>
            <div class="col-6">
                <!-- 2. Only show CountryDetail if a currentCountry is set-->
                <CountryDetail v-bind:country="currentCountry" v-if="currentCountry"/>
            </div>
        </div>
    </div>
</template>

<script>

    // 1. imports
    import axios from 'axios';
    import CountryList from "@/components/CountryList";
    import CountryDetail from "@/components/CountryDetail";

    // 2. constants
    const url = 'https://restcountries.eu/rest/v2/name/';

    // 3. App object
    export default {
        name: 'App',
        // 4. Data/state for this component. Must be a function that
        // returns an object.
        data() {
            return {
                countries: [],
                countryName: '',
                currentCountry: null
            }
        },
        components: {
            CountryDetail,
            CountryList
        },
        // 5. methods for this component. They are called from buttons and event handlers.
        methods: {
            // 5a. search for a list of countries
            searchCountry() {
                if (this.countryName.length < 2) {
                    return;
                }
                axios.get(url + this.countryName)
                    .then(response => {
                        console.log(response.data);
                        this.countries = response.data;
                    })
            },
            // 5b. Set the current country and pass to the detail component
            setCountry(country) {
                this.currentCountry = country;
            },
            // 6. Clear all data
            clear() {
                this.currentCountry = null;
                this.countries = [];
            }
        }
    }
</script>
