// sample applications/countries-vue/src/App.vue
<template>
    <div class="container">
        <h1><img src="./assets/logo.png" height="100"/>Vue Vacation Picker</h1>
        <p>I want to visit:</p>
        <input class="form-control-lg"
               v-model="countryName"
               type="text"
               @keyup.enter="searchCountry"
               placeholder="country name...">
        <button @click="searchCountry"
                class="btn btn-primary">Search
        </button>
        <button class="btn btn-warning" @click="clear()">Clear</button>
        <hr>
        <div class="row">
            <div class="col-6">
                <!-- 1. Pass in the list of countries as a prop. Capture the setCountry event and fire local event handler -->
                <CountryList :countries="countries" @setCountry="setCountry($event)"/>
            </div>
            <div class="col-6">
                <!-- 2. Only show CountryDetail if a currentCountry is set-->
                <CountryDetail v-bind:country="currentCountry" v-if="currentCountry"/>
            </div>
        </div>
    </div>
</template>

<script>

    // 1. imports
    import axios from 'axios';
    import CountryList from "@/components/CountryList";
    import CountryDetail from "@/components/CountryDetail";

    // 2. constants
    const url = 'https://restcountries.eu/rest/v2/name/';

    // 3. App object
    export default {
        name: 'App',
        // 4. Data/state for this component. Must be a function that
        // returns an object.
        data() {
            return {
                countries: [],
                countryName: '',
                currentCountry: null
            }
        },
        components: {
            CountryDetail,
            CountryList
        },
        // 5. methods for this component. They are called from buttons and event handlers.
        methods: {
            // 5a. search for a list of countries
            searchCountry() {
                if (this.countryName.length < 2) {
                    return;
                }
                axios.get(url + this.countryName)
                    .then(response => {
                        console.log(response.data);
                        this.countries = response.data;
                    })
            },
            // 5b. Set the current country and pass to the detail component
            setCountry(country) {
                this.currentCountry = country;
            },
            // 6. Clear all data
            clear() {
                this.currentCountry = null;
                this.countries = [];
            }
        }
    }
</script>

// sample applications/countries-react/src/App.js
import React, {useEffect, useState} from 'react';
import axios from 'axios'
import CountryList from "./components/CountryList";
import CountryDetail from "./components/CountryDetail";
import logo from './img/logo192.png';



// the URL to talk to. Should be in a separate 'globals.js' or the like
const url = 'https://restcountries.eu/rest/v2/name/';

function App() {
    // State hooks: set up hooks for the state of this application
    const [countries, setCountries] = useState([]);
    const [countryName, setCountryName] = useState('');
    const [currentCountry, setCurrentCountry] = useState('');

    // Effect Hook: Log new countries to the console, every time the dependency changes
    useEffect(() => {
        console.log(countries);
    }, [countries]);

    // set the state to hold the current country (could have
    // done that inline, but this is a little cleaner).
    const setCountry = (name) => {
        setCountryName(name)
    };

    // search for the specific country in the textbox.
    // Might be a partial name.
    const searchCountry = () => {
        if (countryName.length < 2) {
            // countryName must be greater that 2 characters
            return;
        }
        // console.log(countryName); // demo
        // fire the http-call
        axios.get(url + countryName)
            .then(response => {
                // console.log(response.data); // demo
                // update the state with the found countries.
                setCountries(response.data);
                //   console.log({countries}); // returns [] or PREVIOUS state, due to the asynchrounous manner of setState() - use an effect hook to capture this.
                setCurrentCountry(''); // reset the current country
            })
    };

    // update the currentCountry, e.g. the country that is clicked on
    const updateCountry = (country) => {
        setCurrentCountry(country)
    };

    // Clear: reset all variables
    const clear = ()=>{
        setCurrentCountry('');
        setCountries([]);
    };

    // UI for the main (top-level) component)
    return (
        <div className="container">
            <h1><img src={logo} width={80} alt=""/>React Vacation Picker</h1>
            <p>I want to visit:</p>
            <input type="text"
                   className="form-control-lg"
                   placeholder="country name..."
                   value={countryName}
                   onKeyUp={(event) => event.key === 'Enter' ? searchCountry() : null}
                   onChange={(event) => setCountry(event.target.value)}
            />
            <button
                onClick={searchCountry}
                className="btn btn-primary">Search
            </button>
            <button
                onClick={clear}
                className="btn btn-warning">Clear
            </button>
            <hr/>
            <h2>Results</h2>
            <div className="row">
                <div className="col-6">
                    {/*Pass in the list of countries and the function to update a country as props */}
                    <CountryList
                        countries={countries}
                        updateCountry={(country) => updateCountry(country)}/>
                </div>
                <div className="col-6">
                    {/*Only show the component if a currentCountry is set*/}
                    { currentCountry && <CountryDetail country={currentCountry}/> }
                </div>
            </div>
        </div>
    );
}

export default App;
