// sample applications/countries-react/src/components/CountryDetail.js
import React from 'react';

function CountryDetail(props) {

    return (
        <>
            <h2>{props.country.name}</h2>
            <ul className="list-group">
                <li className="list-group-item">
                    <img src={props.country.flag} alt="" className="img-fluid"/>
                </li>
                <li className="list-group-item">
                    Capital: {props.country.capital}
                </li>
                <li className="list-group-item">
                    Population: {props.country.population}
                </li>
                <li className="list-group-item">
                    Region: {props.country.subregion}
                </li>
            </ul>
        </>
    );
}

export default CountryDetail;

// sample applications/countries-vue/src/components/CountryDetail.vue
<template>
    <div>
        <h2>{{country.name }}</h2>
        <ul class="list-group">
            <li class="list-group-item"><img :src="country.flag" class="img-fluid" alt=""></li>
            <li class="list-group-item">{{ country.name}}</li>
            <li class="list-group-item">capital: {{ country.capital}}</li>
            <li class="list-group-item">population: {{ country.population}}</li>
            <li class="list-group-item">region: {{ country.subregion}}</li>
        </ul>
    </div>
</template>

<script>
    // This is a display component. It has no logic. It only displays the current country
    // that is passed in. We use extende notation on props here.
    export default {
        name: "CountryDetail",
        props: {
            country:{
                type: Object,
                required: true
            }
        }
    }
</script>
