// sample applications/countries-angular/src/app/country-list/country-list.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';

@Component({
  selector: 'app-country-list',
  templateUrl: './country-list.component.html',
  styleUrls: ['./country-list.component.css']
})
export class CountryListComponent {
  @Input() countries: any[];
  @Output() currentCountry = new EventEmitter<any>();

  // emit an event up to the parent component, to receive the country that is clicked on.
  setCountry(country: any) {
    this.currentCountry.emit(country);
  }
}

<h2>Results</h2>
<ul class="list-group">
  <li
    *ngFor="let country of countries"
    (click)="setCountry(country)"
    class="list-group-item" >
    <img src="{{country.flag}}" alt="" width="80">
    {{ country.name }}
  </li>
</ul>

// sample applications/countries-vue/src/components/CountryList.vue
<template>
    <div>
        <h2>Results</h2>
        <ul class="list-group">
            <li class="list-group-item"
                :key="country.name"
                @click="setCountry(country)"
                v-for="country in countries">
                <img :src="country.flag" alt="" width="80">
                {{ country.name }}
            </li>
        </ul>
    </div>
</template>

<script>
    // This is a display component. It displays a list of passed in countries.
    // It has almost no logic, other than sending an event
    // with the currently selected/clicked country.
    export default {
        name: "CountryList",
        props: {
            countries: {
                type: Array,
                required: true
            }
        },
        methods: {
            setCountry(country){
                this.$emit('setCountry', country)
            }
        }
    }
</script>
