// sample applications/countries-react/src/components/CountryDetail.js
import React from 'react';

function CountryDetail(props) {

    return (
        <>
            <h2>{props.country.name}</h2>
            <ul className="list-group">
                <li className="list-group-item">
                    <img src={props.country.flag} alt="" className="img-fluid"/>
                </li>
                <li className="list-group-item">
                    Capital: {props.country.capital}
                </li>
                <li className="list-group-item">
                    Population: {props.country.population}
                </li>
                <li className="list-group-item">
                    Region: {props.country.subregion}
                </li>
            </ul>
        </>
    );
}

export default CountryDetail;

// sample applications/countries-angular/src/app/country-detail/country-detail.component.ts
import {Component, Input} from '@angular/core';

@Component({
  selector: 'app-country-detail',
  templateUrl: './country-detail.component.html',
  styleUrls: ['./country-detail.component.css']
})
export class CountryDetailComponent {
  @Input() country: any;
}

<h2>{{country.name }}</h2>
<ul class="list-group">
  <li class="list-group-item"><img src="{{country.flag}}" class="img-fluid" alt=""></li>
  <li class="list-group-item">{{ country.name}}</li>
  <li class="list-group-item">capital: {{ country.capital}}</li>
  <li class="list-group-item">population: {{ country.population}}</li>
  <li class="list-group-item">region: {{ country.subregion}}</li>
</ul>
